on:
  "push"

name: "Test"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@master"
      - uses: "oven-sh/setup-bun@v2"
      - run: "bun ci"
      - run: "bun build src --outdir dist --root src"
      - run: "bun test --coverage"
      - run: "bun lint"
